import { COLORS } from '../constants/theme';

// 라이트 모드 색상 (기존 theme.ts 기반)
export const LIGHT_COLORS = {
  // 기본 색상
  BLACK: COLORS.BLACK,
  WHITE: COLORS.WHITE,

  // 회색 계열
  GRAY_50: COLORS.GRAY_50,
  GRAY_100: COLORS.GRAY_100,
  GRAY_200: COLORS.GRAY_200,
  GRAY_300: COLORS.GRAY_300,
  GRAY_400: COLORS.GRAY_400,
  GRAY_500: COLORS.GRAY_500,
  GRAY_600: COLORS.GRAY_600,
  GRAY_700: COLORS.GRAY_700,
  GRAY_800: COLORS.GRAY_800,
  GRAY_900: COLORS.GRAY_900,

  // 대표 색상
  PRIMARY: COLORS.PRIMARY,
  PRIMARY_LIGHT: COLORS.PRIMARY_LIGHT,
  PRIMARY_DARK: COLORS.PRIMARY_DARK,

  // 액센트 색상
  ACCENT: COLORS.ACCENT,
  SUCCESS: COLORS.SUCCESS,
  WARNING: COLORS.WARNING,
  ERROR: COLORS.ERROR,

  // 반투명
  BLACK_10: COLORS.BLACK_10,
  BLACK_20: COLORS.BLACK_20,
  BLACK_30: COLORS.BLACK_30,
  BLACK_50: COLORS.BLACK_50,
  WHITE_10: COLORS.WHITE_10,
  WHITE_20: COLORS.WHITE_20,
  WHITE_50: COLORS.WHITE_50,
} as const;
